baseurl = "https://fizzbuzz.social"
languageCode = "en"
title = "FizzBuzz"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/ZehCnaS34\">ZehCnaS34</a> 2017"
disqusShortname = "FBS"
googleAnalytics = ""
Paginate = 5 # Number of posts per page
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Alexander Sanchez" # Author full name
authorEmail = "alex@fizzbuzz.social" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
# twitter = "ribicemir"
github = "ZehCnaS34"
email = "alex@fizzbuzz.social"
linkedin = "arsanchez34"
codepen = "ZehCnaS34"
rss = "index.xml" # Add this to show RSS button in social.

# [params.matomoAnalytics]
# siteID = 1
# rootURL = "//matomo.example.com/"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
